#!/bin/sh
# -*- sh -*-

statsfile=${statsfile:-/var/lib/munin/plugin-state/huawei-hg612-munin-output.txt}

: << =cut

=head1 NAME

Line Stats - Plugin to get Huawei HG612 line stats

=head1 NOTES

Fetches current Power

=head1 AUTHOR

Adam Smith

=head1 LICENSE

GPL

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then

        echo "host_name hg612"
        echo "graph_title Aggregate Tx Power"
        echo 'graph_args --base 1000'
        echo 'graph_vlabel Actual Aggregate Tx Power (dBm)'
        echo 'graph_category hg612'
        echo 'graph_scale no'
        echo 'downstream.label Downstream'
        echo 'downstream.draw LINE'
        echo 'upstream.label Upstream'
        echo 'upstream.draw LINE'
        exit 0
fi;


echo -n "downstream.value "
echo $(grep Pwr $statsfile  | head -n 1 | awk '{ print $2 }')
echo -n "upstream.value "
echo $(grep Pwr $statsfile  | head -n 1 | awk '{ print $3 }')

	exit 0
fi
